name: Source Distribution

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    name: Python 3.9

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64

      - name: Install test dependencies
        run: pip install wheel flake8 pytest twine

      - name: Flake8
        # stop the build if there are Python syntax errors or undefined names
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        run: |
          flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Install libsnappy-dev
        run: sudo apt-get install libsnappy-dev

      - name: Generate source distribution
        run: python setup.py sdist

      - name: Clean up sources
        # this cleans up the sources to make sure `import snappy` uses the sdist
        # an alternative would be to run pytest in a different working directory
        run: rm -rf setup.py ./snappy

      - name: Install python-snappy sdist
        run: pip install dist/python-snappy*.tar.gz

      - name: Pytest
        run: pytest --verbose test_snappy.py

      - name: Archive sdist
        uses: actions/upload-artifact@v2
        with:
          name: python_snappy-${{ matrix.pep-425-tag }}-manylinux
          path: dist/python-snappy*.tar.gz

      - name: Publish sdist to PyPI
        if: startsWith(github.ref, 'refs/tags/0.')
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload dist/python-snappy*.tar.gz
